use("Taller");

// db.createCollection(
//     "Estudiantes",
//     {
//       validator: {
//         $jsonSchema: {
//           bsonType: "object",
//           required: ["nombre", "edad", "direccion", "tel", "materias"],
//           properties: {
//             nombre: {
//               bsonType: "string",
//               description: "debe ser una cadena y es requerido",
//             },
//             edad: {
//               bsonType: "int",
//               minimum: 0,
//               maximum: 120,
//               description: "debe ser un número entero entre 0 y 120",
//             },
//             direccion: {
//               bsonType: "string",
//               description: "debe ser una cadena y es requerido",
//             },
//             tel: {
//               bsonType: "int",
//               description: "debe ser un número entero",
//             },
//             materias: {
//               bsonType: "array",
//               minItems: 1,
//               uniqueItems: true,
//               items: {
//                 bsonType: "string",
//                 description: "debe ser una cadena",
//               },
//               description: "debe ser un array de materias con al menos un elemento",
//             },
//           },
//         },
//       },
//     }
//   );

// INSERTANTO UN DATO
//   db.Estudiantes.insertOne({
//     nombre: "Juan",
//     edad: 13,
//     direccion: "Calle 12",
//     tel: 245224,
//     materias: ["Algebra", "Matematicas", "Historia"],
//   });

// INSERTANTO 40 DATOS
db.Estudiantes.insertMany([
  {
    nombre: "Carlos",
    edad: 18,
    direccion: "Calle 22",
    tel: 245224,
    materias: ["Algebra", "Matematicas"],
  },

  {
    nombre: "María",
    edad: 16,
    direccion: "Calle 25",
    tel: 234567,
    materias: ["Matematicas", "Algebra"],
  },

  {
    nombre: "Pedro",
    edad: 55,
    direccion: "Calle 34",
    tel: 8904563,
    materias: ["Historia", "Matematicas"],
  },

  {
    nombre: "Laura",
    edad: 25,
    direccion: "Calle 36",
    tel: 1345670,
    materias: ["Matematicas", "Historia"],
  },

  {
    nombre: "Ana",
    edad: 90,
    direccion: "Calle 76",
    tel: 1678900,
    materias: ["Historia"],
  },

  {
    nombre: "Luis",
    edad: 56,
    direccion: "Calle 13",
    tel: 7865643,
    materias: ["Matematicas"],
  },

  {
    nombre: "Marta",
    edad: 56,
    direccion: "Calle 90",
    tel: 8900087,
    materias: ["Historia"],
  },

  {
    nombre: "Marta",
    edad: 56,
    direccion: "Calle 90",
    tel: 8900087,
    materias: ["Historia"],
  },

  {
    nombre: "David",
    edad: 17,
    direccion: "Calle 100",
    tel: 123456,
    materias: ["Algebra"],
  },

  {
    nombre: "Elena",
    edad: 20,
    direccion: "Calle 21",
    tel: 3678901,
    materias: ["Historia"],
  },

  {
    nombre: "José",
    edad: 20,
    direccion: "Carrera 21",
    tel: 890745,
    materias: ["Matematicas"],
  },

  {
    nombre: "Isabel",
    edad: 78,
    direccion: "Carrera 12",
    tel: 765432,
    materias: ["Algebra", "Matematicas", "Historia"],
  },

  {
    nombre: "Miguel",
    edad: 23,
    direccion: "Carrera 17",
    tel: 789000,
    materias: ["Algebra", "Matematicas", "Historia"],
  },

  {
    nombre: "Sofía",
    edad: 45,
    direccion: "Carrera 77",
    tel: 567890,
    materias: ["Algebra", "Matematicas", "Historia"],
  },

  {
    nombre: "Pablo",
    edad: 75,
    direccion: "Carrera 99",
    tel: 345678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },

  {
    nombre: "Lucía",
    edad: 55,
    direccion: "Carrera 1",
    tel: 765432,
    materias: ["Algebra", "Matematicas", "Historia"],
  },

  {
    nombre: "Alejandro",
    edad: 12,
    direccion: "Carrera 10",
    tel: 987654,
    materias: ["Algebra", "Matematicas", "Historia"],
  },

  {
    nombre: "Carmen",
    edad: 55,
    direccion: "Carrera 15",
    tel: 145678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },

  {
    nombre: "Daniel",
    edad: 45,
    direccion: "carrera 15",
    tel: 876543,
    materias: ["Matematicas", "Historia"],
  },

  {
    nombre: "Paula",
    edad: 45,
    direccion: "carrera 89",
    tel: 678543,
    materias: ["Matematicas", "Historia"],
  },

  {
    nombre: "Jorge",
    edad: 37,
    direccion: "calle 89",
    tel: 123456,
    materias: ["Matematicas", "Historia"],
  },

  {
    nombre: "Jorge",
    edad: 90,
    direccion: "calle 55",
    tel: 3456789,
    materias: ["Historia"],
  },

  {
    nombre: "Sara",
    edad: 30,
    direccion: "calle 32",
    tel: 13458900,
    materias: ["Algebra"],
  },

  {
    nombre: "Javier",
    edad: 30,
    direccion: "calle 21",
    tel: 123456,
    materias: ["Historia"],
  },

  {
    nombre: "Raquel",
    edad: 49,
    direccion: "calle 15",
    tel: 123456,
    materias: ["Matematicas"],
  },

  {
    nombre: "Francisco",
    edad: 57,
    direccion: "calle 75",
    tel: 890324,
    materias: ["Historia"],
  },

  {
    nombre: "Martina",
    edad: 25,
    direccion: "calle 34",
    tel: 456789,
    materias: ["Matematicas", "Historia"],
  },

  {
    nombre: "Antonio",
    edad: 10,
    direccion: "carrera 21",
    tel: 678906,
    materias: ["Matematicas", "Algebra"],
  },

  {
    nombre: "Beatriz",
    edad: 25,
    direccion: "carrera 45",
    tel: 134598,
    materias: ["Matematicas", "Algebra"],
  },

  {
    nombre: "Manuel",
    edad: 25,
    direccion: "carrera 55",
    tel: 556780,
    materias: ["Matematicas", "Historia"],
  },
  
  {
    nombre: "Claudia",
    edad: 25,
    direccion: "carrera 35",
    tel: 678900,
    materias: ["Algebra", "Historia", "Matematicas"],
  },

  {
    nombre: "Alberto",
    edad: 29,
    direccion: "calle 55",
    tel: 556780,
    materias: ["Algebra", "Historia", "Matematicas"],
  },

  {
    nombre: "Andrea",
    edad: 85,
    direccion: "carrera 89",
    tel: 456789,
    materias: ["Algebra", "Historia", "Matematicas"],
  },

  {
    nombre: "Fernando",
    edad: 25,
    direccion: "carrera 55",
    tel: 556780,
    materias: ["Matematicas", "Historia"],
  },

  {
    nombre: "Manuel",
    edad: 14,
    direccion: "calle 75",
    tel: 890067,
    materias: ["Matematicas", "Historia"],
  },

  {
    nombre: "Natalia",
    edad: 55,
    direccion: "calle 25",
    tel: 678921,
    materias: ["Matematicas", "Historia"],
  },

  {
    nombre: "Sergio",
    edad: 95,
    direccion: "calle 35",
    tel: 123456,
    materias: ["Matematicas", "Historia"],
  },

  {
    nombre: "Manuel",
    edad: 25,
    direccion: "carrera 55",
    tel: 556780,
    materias: ["Historia"],
  },

  {
    nombre: "Victoria",
    edad: 16,
    direccion: "calle 79",
    tel: 456700,
    materias: ["Algebra"],
  },

  {
    nombre: "Adrián",
    edad: 48,
    direccion: "calle 45",
    tel: 876543,
    materias: ["Matematicas"],
  },
  // aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  {
    nombre: "Carlos",
    edad: 18,
    direccion: "Calle 22",
    tel: 245224,
    materias: ["Algebra", "Matematicas"],
  },
  {
    nombre: "María",
    edad: 16,
    direccion: "Calle 25",
    tel: 234567,
    materias: ["Matematicas", "Algebra"],
  },
  {
    nombre: "Pedro",
    edad: 55,
    direccion: "Calle 34",
    tel: 8904563,
    materias: ["Historia", "Matematicas"],
  },
  {
    nombre: "Laura",
    edad: 25,
    direccion: "Calle 36",
    tel: 1345670,
    materias: ["Matematicas", "Historia"],
  },
  {
    nombre: "Ana",
    edad: 90,
    direccion: "Calle 76",
    tel: 1678900,
    materias: ["Historia"],
  },
  {
    nombre: "Luis",
    edad: 56,
    direccion: "Calle 13",
    tel: 7865643,
    materias: ["Matematicas"],
  },
  {
    nombre: "Marta",
    edad: 56,
    direccion: "Calle 90",
    tel: 8900087,
    materias: ["Historia"],
  },
  {
    nombre: "Marta",
    edad: 56,
    direccion: "Calle 90",
    tel: 8900087,
    materias: ["Historia"],
  },
  {
    nombre: "David",
    edad: 17,
    direccion: "Calle 100",
    tel: 123456,
    materias: ["Algebra"],
  },
  {
    nombre: "Elena",
    edad: 20,
    direccion: "Calle 21",
    tel: 3678901,
    materias: ["Historia"],
  },
  {
    nombre: "José",
    edad: 20,
    direccion: "Carrera 21",
    tel: 890745,
    materias: ["Matematicas"],
  },
  {
    nombre: "Isabel",
    edad: 78,
    direccion: "Carrera 12",
    tel: 765432,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Miguel",
    edad: 23,
    direccion: "Carrera 17",
    tel: 789000,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sofía",
    edad: 45,
    direccion: "Carrera 77",
    tel: 567890,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Pablo",
    edad: 75,
    direccion: "Carrera 99",
    tel: 345678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucía",
    edad: 55,
    direccion: "Carrera 1",
    tel: 765432,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Alejandro",
    edad: 12,
    direccion: "Carrera 10",
    tel: 987654,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carmen",
    edad: 55,
    direccion: "Carrera 15",
    tel: 145678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Daniel",
    edad: 45,
    direccion: "carrera 15",
    tel: 876543,
    materias: ["Matematicas", "Historia"],
  },
  {
    nombre: "Paula",
    edad: 45,
    direccion: "carrera 89",
    tel: 678543,
    materias: ["Matematicas", "Historia"],
  },
  {
    nombre: "Jorge",
    edad: 37,
    direccion: "calle 89",
    tel: 123456,
    materias: ["Matematicas", "Historia"],
  },
  {
    nombre: "Jorge",
    edad: 90,
    direccion: "calle 55",
    tel: 3456789,
    materias: ["Historia"],
  },
  {
    nombre: "Sara",
    edad: 30,
    direccion: "calle 32",
    tel: 13458900,
    materias: ["Algebra"],
  },
  {
    nombre: "Javier",
    edad: 30,
    direccion: "calle 21",
    tel: 123456,
    materias: ["Historia"],
  },
  {
    nombre: "Raquel",
    edad: 49,
    direccion: "calle 15",
    tel: 123456,
    materias: ["Matematicas"],
  },
  {
    nombre: "Francisco",
    edad: 57,
    direccion: "calle 75",
    tel: 890324,
    materias: ["Historia"],
  },
  {
    nombre: "Martina",
    edad: 25,
    direccion: "calle 34",
    tel: 456789,
    materias: ["Matematicas", "Historia"],
  },
  {
    nombre: "Antonio",
    edad: 10,
    direccion: "carrera 21",
    tel: 678906,
    materias: ["Matematicas", "Algebra"],
  },
  {
    nombre: "Beatriz",
    edad: 25,
    direccion: "carrera 45",
    tel: 134598,
    materias: ["Matematicas", "Algebra"],
  },
  {
    nombre: "Manuel",
    edad: 25,
    direccion: "carrera 55",
    tel: 556780,
    materias: ["Matematicas", "Historia"],
  },
  {
    nombre: "Luisa",
    edad: 19,
    direccion: "Carrera 20",
    tel: 456789,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Miguel",
    edad: 21,
    direccion: "Calle 30",
    tel: 567890,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sara",
    edad: 18,
    direccion: "Carrera 10",
    tel: 678901,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carlos",
    edad: 20,
    direccion: "Avenida 3",
    tel: 789012,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucas",
    edad: 22,
    direccion: "Calle 25",
    tel: 890123,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Laura",
    edad: 24,
    direccion: "Carrera 18",
    tel: 901234,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Diego",
    edad: 25,
    direccion: "Calle 32",
    tel: 123456,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Elena",
    edad: 26,
    direccion: "Avenida 8",
    tel: 234567,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sofía",
    edad: 27,
    direccion: "Carrera 12",
    tel: 345678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Pablo",
    edad: 28,
    direccion: "Calle 40",
    tel: 456789,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carlos",
    edad: 29,
    direccion: "Avenida 5",
    tel: 567890,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucas",
    edad: 30,
    direccion: "Carrera 30",
    tel: 678901,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Laura",
    edad: 31,
    direccion: "Calle 15",
    tel: 789012,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Diego",
    edad: 32,
    direccion: "Avenida 10",
    tel: 890123,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Elena",
    edad: 33,
    direccion: "Carrera 7",
    tel: 901234,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sofía",
    edad: 34,
    direccion: "Calle 20",
    tel: 123456,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Pablo",
    edad: 35,
    direccion: "Avenida 12",
    tel: 234567,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carlos",
    edad: 36,
    direccion: "Carrera 25",
    tel: 345678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Javier",
    edad: 37,
    direccion: "Calle 35",
    tel: 456789,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucas",
    edad: 38,
    direccion: "Carrera 15",
    tel: 567890,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Ana",
    edad: 39,
    direccion: "Avenida 10",
    tel: 678901,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "María",
    edad: 40,
    direccion: "Carrera 12",
    tel: 789012,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Miguel",
    edad: 41,
    direccion: "Calle 18",
    tel: 890123,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sara",
    edad: 42,
    direccion: "Avenida 5",
    tel: 901234,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carlos",
    edad: 43,
    direccion: "Carrera 30",
    tel: 123456,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucas",
    edad: 44,
    direccion: "Calle 25",
    tel: 234567,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Laura",
    edad: 45,
    direccion: "Avenida 12",
    tel: 345678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Diego",
    edad: 46,
    direccion: "Calle 30",
    tel: 456789,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Elena",
    edad: 47,
    direccion: "Avenida 3",
    tel: 567890,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sofía",
    edad: 48,
    direccion: "Carrera 10",
    tel: 678901,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Pablo",
    edad: 49,
    direccion: "Calle 40",
    tel: 789012,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carlos",
    edad: 50,
    direccion: "Avenida 5",
    tel: 890123,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucas",
    edad: 51,
    direccion: "Carrera 30",
    tel: 901234,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Laura",
    edad: 52,
    direccion: "Calle 15",
    tel: 123456,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Diego",
    edad: 53,
    direccion: "Avenida 10",
    tel: 234567,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Elena",
    edad: 54,
    direccion: "Carrera 7",
    tel: 345678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sofía",
    edad: 55,
    direccion: "Calle 20",
    tel: 456789,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Pablo",
    edad: 56,
    direccion: "Avenida 12",
    tel: 567890,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carlos",
    edad: 57,
    direccion: "Carrera 25",
    tel: 678901,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Javier",
    edad: 58,
    direccion: "Calle 35",
    tel: 789012,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucas",
    edad: 59,
    direccion: "Carrera 15",
    tel: 890123,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Ana",
    edad: 60,
    direccion: "Avenida 10",
    tel: 901234,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "María",
    edad: 61,
    direccion: "Carrera 12",
    tel: 123456,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Miguel",
    edad: 62,
    direccion: "Calle 18",
    tel: 234567,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sara",
    edad: 63,
    direccion: "Avenida 5",
    tel: 345678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carlos",
    edad: 64,
    direccion: "Carrera 30",
    tel: 456789,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucas",
    edad: 65,
    direccion: "Calle 25",
    tel: 567890,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Laura",
    edad: 66,
    direccion: "Avenida 12",
    tel: 678901,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Diego",
    edad: 67,
    direccion: "Calle 30",
    tel: 789012,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Elena",
    edad: 68,
    direccion: "Avenida 3",
    tel: 890123,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sofía",
    edad: 69,
    direccion: "Carrera 10",
    tel: 901234,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Pablo",
    edad: 70,
    direccion: "Calle 40",
    tel: 123456,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carlos",
    edad: 71,
    direccion: "Avenida 5",
    tel: 234567,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucas",
    edad: 72,
    direccion: "Carrera 30",
    tel: 345678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Laura",
    edad: 73,
    direccion: "Calle 15",
    tel: 456789,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Diego",
    edad: 74,
    direccion: "Avenida 10",
    tel: 567890,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Elena",
    edad: 75,
    direccion: "Carrera 7",
    tel: 678901,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sofía",
    edad: 76,
    direccion: "Calle 20",
    tel: 789012,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Pablo",
    edad: 77,
    direccion: "Avenida 12",
    tel: 890123,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carlos",
    edad: 78,
    direccion: "Carrera 25",
    tel: 901234,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Javier",
    edad: 79,
    direccion: "Calle 35",
    tel: 123456,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucas",
    edad: 80,
    direccion: "Carrera 15",
    tel: 234567,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Ana",
    edad: 81,
    direccion: "Avenida 10",
    tel: 345678,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "María",
    edad: 82,
    direccion: "Carrera 12",
    tel: 456789,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Miguel",
    edad: 83,
    direccion: "Calle 18",
    tel: 567890,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Sara",
    edad: 84,
    direccion: "Avenida 5",
    tel: 678901,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Carlos",
    edad: 85,
    direccion: "Carrera 30",
    tel: 789012,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Lucas",
    edad: 86,
    direccion: "Calle 25",
    tel: 890123,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Laura",
    edad: 87,
    direccion: "Avenida 12",
    tel: 901234,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
  {
    nombre: "Diego",
    edad: 88,
    direccion: "Calle 30",
    tel: 123456,
    materias: ["Algebra", "Matematicas", "Historia"],
  },
]);

